on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Upload files via FTP
      uses: sebastianpopp/ftp-action@v1
      with:
        host: ftpupload.net
        user: ezyro_38543176
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "./"
        remoteDir: "/public_html/"

        