on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4  # Change back to this action if it's working
        with:
          server: ftpupload.net
          username: ezyro_38543176
          password: f91bbeacb
          local-dir: ./
          server-dir: ./